[platformio]
src_dir = .

[env]
framework = arduino
build_src_filter = +<*.cpp> +<tests/embedded/main.cpp>

[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32dev

[env:esp8266]
platform = espressif8266
board = nodemcuv2
